//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tasktracker.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TaskTrDBEntitiesContext : DbContext
    {
        public TaskTrDBEntitiesContext()
            : base("name=TaskTrDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HistoryTable> HistoryTables { get; set; }
        public virtual DbSet<StoryTable> StoryTables { get; set; }
    }
}
